project:
  type: website
  output-dir: docs
  
resources:
  - images/logo.png
  - images/Performance_measures_header_main.webp
  - images/PM_Safety.png
website:
  title: "Palm Beach MPO Dashboard"

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    code-fold: true
